export const SEARCH_SONGS_BY_LYRICS = 'SEARCH_SONGS_BY_LYRICS';
export const GET_ARTIST_BY_ID = 'GET_ARTIST_BY_ID';
export const GET_ARTIST_ALBUMS_BY_ID = 'GET_ARTIST_ALBUMS_BY_ID';
export const GET_ALBUM_BY_ID = 'GET_ALBUM_BY_ID';
export const SET_LOADING = 'SET_LOADING';
